### ISSUE TITLE
Survey Question on the For loop in source file src/reduction.c line 60

### ISSUE THREAD

**Issue by pdhung3012** [adhithadias/openmp#1]
Hello Sir/ Madam
We are from a research group at Iowa State University, USA. We want to do a survey on Github developers on the methods they used for paralleling their code. To do the survey, We want to ask three questions:

1. Have you ever tried to add pragma for that 'for' loop?.

2. How much confidence do you have about the correctness of this implementation? You can choose from 1-5 with 1 as the lowest confidence score and 5 as the highest confidence.

3. (Optional) Do you actually run (interpret the code with compilation and pass input/get output) the code? Yes/No
- If yes, can you provide the information of what are the input and expected output of this program (the input that caused the program to run through this for-loop).

The for loop is from line 60 of file https:/github.com/adhithadias/openmp-mpi-examples/blob/master/src/reduction.c
Here is a part of the code:

nan
for (int i = 0; i < 1000000; i++)
{
  y += x[i];
}

Sincerely thanks

**Comment by adhithadias** [comment]
1. Yes, look at lines 79, 96, and 120 lines of the file https:/github.com/adhithadias/openmp-mpi-examples/blob/master/src/reduction.c -- same operation is performed by using `#pragma omp parallel for` and `#pragma omp parallel for reduction`
2. 5
3. Yes, this is just a reduction to get the sum of a double array. Look at the array definition and initialisation.
